### PR TITLE
Whatever

### PR DESCRIPTION
**Pull request by SunburntRock89**

### CODE REVIEW

**Comment by TTtie** [comment]
it's not whatever @KingDGrizzle

**Comment by TTtie** [comment]
the right license text is [here](http://www.wtfpl.net/txt/copying/)

**Comment by SunburntRock89** [comment]
Yes, but this is the Vlag License, not the Sam Hocevar license, and its Version 420, not Version 2, and its from 2017, not 2004

**Comment by TTtie** [comment]
>not the Sam Hocevar license

Doesn't really matter, the copyright text is an example, so is the year. 

> and its Version 420, not Version 2

No one cares about versions :eyes:

**Comment by SunburntRock89** [comment]
TTie why does it matter? Its the same text but it sounds better. 

_**# Also Eris is shit.**_

**Comment by SunburntRock89** [comment]
Hey wait what does this button do? https://i.squaddy.xyz/sE4jkz.png

**Comment by TTtie** [comment]
deletes the branch

**Comment by TTtie** [comment]
like a charm

**Comment by SunburntRock89** [comment]
huh, maybe I should press that

**Pull request merged**
