### PR TITLE
Change the Gordon command's images

### PR DESCRIPTION
**Pull request by mrdnomaid**

### CODE REVIEW

**Comment by mrdnomaid** [comment]
Oh whoops, forgot to add the URL to the start of the image embed

**Comment by mrdnomaid** [comment]
There we go

**Comment by KingDGrizzle** [comment]
Travia check still ded

**Comment by mrdnomaid** [comment]
It's complaining because of some trailing space in the example command. Didn't even touch it.

**Comment by KingDGrizzle** [comment]
Is this PR still valid @mrdnomaid?

**Comment by mrdnomaid** [comment]
I have no idea. The folder is still up though.

**Pull request merged**
